### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.ArgumentBinder#1]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by xforever1313** [comment]
I don't have any concerns.  If something happens to me or if I get too busy with other things I wouldn't want the addin to get stale.

I added cake-contrib as a user on NuGet.  Can you confirm that it went through okay?  Once its confirmed I'll close this issue.

**Comment by gep13** [comment]
@xforever1313 thank you very much for doing this, I really appreciate it!  I have just accepted the request!

>@xforever1313 said...
 If something happens to me or if I get too busy with other things I wouldn't want the addin to get stale.

Yip, this is exactly why I create the Cake Contrib Organisation on NuGet and also on GitHub, so that the development effort can be shared between other members of the team, when "life" gets in the way.

Would you also be interested in transferring this repository into the Cake Contrib GitHub Organisation?  You would have complete control over the repository after the transfer, in the same way as you do now, it would just live in an Organisation, where others could be added easily to help out, if required.

**Comment by xforever1313** [comment]
> Would you also be interested in transferring this repository into the Cake Contrib GitHub Organisation? You would have complete control over the repository after the transfer, in the same way as you do now, it would just live in an Organisation, where others could be added easily to help out, if required.

Yeah! I'm definitely interested in doing that... I'll just need instructions on how to proceed :).

**Comment by gep13** [comment]
That is great news! The process for moving a repository into the Organisation is documented here:

https://github.com/cake-contrib/Home/blob/master/README.md#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

Only the first step needs to be completed by you, the rest done by a Cake Team member.

The reason for transferring to an individual first, rather than straight into the Organisation is a limitation on the part of GitHub. If you wanted to transfer it to my account, gep13, I could start the process.

**Comment by xforever1313** [comment]
Understood.  I just put in the transfer request to you.

**Comment by gep13** [comment]
@xforever1313 that is great!  Thanks for doing that!  I have completed the initial part of the transfer into the Organisation, and I have sent an invite through to add you to the Organisation, with full admin rights to this repository.  There will be a little bit more work that I need to do in order to setup a project in AppVeyor, but I should be able to completer that work later this evening.

Can you let me know if you use Twitter and Slack?  It would be good to follow you on Twitter (although I might already have done this) and also to invite you into the Cake Contrib Slack Team, where you can ask questions of other Cake Addin Maintainers.

Please let me know if you have any questions.

**Comment by xforever1313** [comment]
My Twitter is the same as my GitHub username (https://twitter.com/xforever1313).

I... actually don't have a Slack... I never needed one :man_shrugging:

**Comment by gep13** [comment]
@xforever1313 thank you for the information.

If you did want to tip your toes into Slack, then feel free to DM me an email address on Twitter (my DM's are open) and I can send you an invite.  It is a low traffic Slack, but there are a lot of Cake Addin Maintainers in there, so if you ever had a question about anything, it is a good place to ask questions.

I believe that everything is now setup in terms of transferring this repository into the Cake Contrib Organisation.  Thanks again for doing this, I really appreciate it!
